### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ciaranodriscoll** [ave-63/attendant.r#1]
Hi, trying to run but getting an error. The documents are named accurately so not sure what the issue is 

Error in output_matches[j, 2] : subscript out of bounds
Execution halted

:: USER OPTIONS:

:: Path to folder containing all your downloaded csv files. You must edit this!
set INPUT_DIRECTORY= "C:\Users\CAPS - Documents\Attendance Records\Module 2 zoom data\"

:: Path to folder where you want your result csv files to go. You must edit this!
set OUTPUT_DIRECTORY= "C:\Users\CAPS - Documents\Attendance Records\summaries\"

:: The current year.
set YEAR=2021

:: Do not mess with anything below.
"C:\Program Files\R\R-4.0.2\bin\Rscript.exe" ./attendant.r %INPUT_DIRECTORY% %OUTPUT_DIRECTORY% %YEAR%
pause

**Comment by ave-63** [comment]
Hey, I discovered the problem and I think I fixed it if you wanna download
it again.

Basically, I just added this "if(nrow(output_matches > 0)){ ... } around
the code in attendant.r with the error like so, if you wanna change it
yourself:

        output_exists <- FALSE
        if(nrow(output_matches > 0)){
            for(j in 1:nrow(output_matches)){
                if(!is.na(output_matches[j,2]) && inputs$course_id[i] ==
output_matches[j,2]){
                    output_exists <- TRUE
                    ## Remove rows from inputs that are already in output
file w/ same page_range, dl_date
                    existing_days <-
colnames(read.csv(paste0(OUTPUT_DIRECTORY, output_matches[j,1])))
                    for(k in 1:nrow(inputs)){
                        if(inputs$course_id[k] == output_matches[j,2] &&
                           inputs$col_name[k] %in% existing_days){
                            keepers[k] <- FALSE
                        }
                    }
                }
            }
        }


Interestingly, this error should have happened to anyone using the program
for the first time. It didn't happen to me because when I created it, I
already made empty output files for testing. So you are actually the first
person other than me to use the program! Congratulations! I hope it works.

Ben Smith

**Comment by ciaranodriscoll** [comment]
Thanks for this Ben. If I can get this working it will extremely useful.
I'm now hitting an additional error where it cannot open files or
connections to read and save files.
It looks like it might be due to the use of the paste0 function not using a
separator (i.e. paste0(INPUT_DIRECTORY, inputs$file_name[i])  leads
to C:\Users\CAPS - Documents\Attendance Records\Module 2 zoom
dataCAP_att_2-03.csv

INPUT_DIRECTORY is set as  C:\Users\CAPS - Documents\Attendance
Records\Module 2 zoom data\ but it seems to drop the final \ for some
reason.

I've tried changing to the paste function and adding in sep = " \ " but it
doesn't add in the separator only inserts a space.

BW

Ciaran

**Comment by ciaranodriscoll** [comment]
I got it working in the end. Btw there was a need to change a few other bits relating to how it reads the headings. I don't know whether zoom has altered them since you wrote the script. Thanks for this! BW

**Comment by ave-63** [comment]
Excellent, I'm glad it's working.  I think the headings for my zoom reports
must be different than for yours; probably a setting that your sys admins
set differently than mine.

By the way, I'm planning on re-writing this program in python over the
summer. I also wrote a similar script for helping some of my coworkers
grade assignments, and everyone seems to have trouble installing R and its
libraries, in addition to problems with the three different kinds of shell
scripts for Mac, windows, and linux. If I do it in python, I can use
PyInstaller to create executable files for mac & windows that don't require
the user to install anything. And then just put the configuration options
in a JSON or YAML file that is the same for any OS.  Or you might just be
happy with the R version now that you've got it working.

Anyway, thanks for using the program!
Ben

**Comment by ciaranodriscoll** [comment]
Sounds good. I have some colleagues on other courses I'm going to suggest
it to, the simpler the configuration for them the better!
